### ISSUE TITLE
Angular 7 + Nativescript

### ISSUE THREAD

**Issue by ccll86** [triniwiz/nativescript-twitter#8]
Hello people,

I'm a new user using NativeScript and now my head is breaking. 

I'm stuck on CustomAppDelegate class, Nativescript can't find variable Twitter on applicationDidFinishLaunchingWithOptions , i've been looking at the git project master but nothing is working.

Any suggestions please?

**Comment by Carli0s** [comment]
Hi, 
This is working for me,  the problem is on file custom-app-delegate.ts.

This is now my file.

import * as utils from "tns-core-modules/utils/utils";

declare const  **TWTRTwitter**;

export class CustomAppDelegate extends UIResponder implements UIApplicationDelegate {

    public static ObjCProtocols = [UIApplicationDelegate];

    applicationDidFinishLaunchingWithOptions(application, launchOptions) {
        console.log("applicationDidFinishLaunchingWithOptions");
        utils.ios.getter(**TWTRTwitter**,**TWTRTwitter**.sharedInstance).startWithConsumerKeyConsumerSecret("mykeySmall" ,"mykeyLong");
        return true;
    }
    applicationOpenURLOptions(application, url, options) {
        return utils.ios.getter(**TWTRTwitter**,**TWTRTwitter**.sharedInstance).applicationOpenURLOptions(application, url, options);
    }
}

* Change instances Twitter for  TWTRTwitter.

**Comment by ccll86** [comment]
Hi, 
This is working for me,  the problem is on file custom-app-delegate.ts.

This is now my file.

import * as utils from "tns-core-modules/utils/utils";

declare const  **TWTRTwitter**;

export class CustomAppDelegate extends UIResponder implements UIApplicationDelegate {

    public static ObjCProtocols = [UIApplicationDelegate];

    applicationDidFinishLaunchingWithOptions(application, launchOptions) {
        console.log("applicationDidFinishLaunchingWithOptions");
        utils.ios.getter(TWTRTwitter,TWTRTwitter.sharedInstance).startWithConsumerKeyConsumerSecret("mykeySmall" ,"mykeyLong");
        return true;
    }
    applicationOpenURLOptions(application, url, options) {
        return utils.ios.getter(TWTRTwitter,TWTRTwitter.sharedInstance).applicationOpenURLOptions(application, url, options);
    }
}

* Change instances Twitter for  TWTRTwitter.
